name: Feature Request
description: Suggest a new feature.
labels: ["enhancement"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing feature request for this?
      description: Please search to see if there is already a Github issue for the feature you are requesting.
      options:
      - label: I have searched the existing issues
        required: true
  - type: dropdown
    id: add-on
    attributes:
      label: Add-on
      description: What add-on are you referring to?
      options:
        - Doorbell
  - type: textarea
    id: feature
    attributes:
      label: Your feature request
      description: How do you think the add-on could be improved/what is currently missing?
