blueprint:
  name: Doorbell ringing
  description: >
    **Version: 0.1**
    This blueprint shows an example automation that displays a Home Assistant notification when a someone rings the doorbell

  domain: automation
  input:
    doorbell_sensor:
      name: Doorbell sensor *
      description: The binary sensor associated with the doorbell ringing
      selector:
        entity:
          domain: binary_sensor

variables:
  doorbell_sensor: !input doorbell_sensor

trigger:
  - platform: state
    entity_id: !input doorbell_sensor
    to: "on"

action:
  - service: persistent_notification.create
    data:
      title: "Someone is at the door!"
      message: "Someone ringed the doorbell"
